application: caminito-billbill
version: dev
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: index.html
  upload: index.html
  login: required
  secure: always

- url: /(.*\.(html|css|js|png|gif|jpg|svg|eot|ttf|woff))
  static_files: \1
  upload: .*\.(html|css|js|png|gif|jpg|svg|eot|ttf|woff)
  login: required
  secure: always
